### ISSUE TITLE
找不到模块mmkv

### ISSUE THREAD

**Issue by yaleimeng** [R0uter/LoginputEngine#1]
$ python main.py 
Traceback (most recent call last):  
File "main.py", line 3, in     from train import data_produce, get_transition_from_data, get_smooth_transition                                                                                                     File "C:\Users\itibia\Downloads\LoginputEngine-master\LoginputEngine-master\train\get_transition_from_data.py", line 11, in                                                     import mmkv    
ModuleNotFoundError: No module named 'mmkv'
自己找了半天，可能是对应到 https://github.com/Tencent/MMKV吧？但这个是C++库，似乎要编译了才能用。

另外项目中似乎也没有用于train的语料内容或者格式介绍。

感谢作者开源分享，同时希望维护一下相关内容，让项目成为一个简单配置环境就可以跑起来的demo。

**Comment by R0uter** [comment]
这几天正在活跃重构这个项目……昨天才加的mmkv，今天已经给去掉了，我正在跑，已经换回lmdb了你试试，等跑完了我再更新后续。

回头我把语料啥的格式也写一下哈。

感谢关注。

**Comment by R0uter** [comment]
关于语料的说明也补上了，mmkv的依赖已经去掉，还是用回了lmdb，我对生成的过程进行了优化，仅在合并数据的过程中使用LMDB，最终写出的还是txt，并且优化了文件长度计算机制，现在不用等加载了。
